### ISSUE TITLE
소급 적용을 금지해야 합니다.

### ISSUE THREAD

**Issue by nnnlog** [Flug-in-Fabrik/Fabrik-EULA#2]
![image](https://user-images.githubusercontent.com/20399222/73943038-6717e380-4933-11ea-90f1-a921eef56a3d.png)
라이선스 전문을 플러그인 코드 내 주석으로 삽입하는 형태로 사용자가 알도록 하거나, 사용자가 동의받는 형태로 배포해야 합니다.

라이선스 전문을 README 링크(branch)로 연결하는 것은 이미 배포된 플러그인에 대해서 무단으로 라이선스를 변경하는 것이며, 위의 방식으로 바뀐 라이선스는 효력이 없습니다.

**Comment by sipleUI** [comment]
답장이 늦어죄송합니다. 최대한빨리 개선을하겠습니다. 감사합니다
